# coding=utf-8

SEX_MALE = "MALE"
SEX_FEMALE = 'FEMALE'
SEX_UNDEFINED = "UNDEFINED"

SEX_TYPES = (
    (SEX_MALE, 'Male'),
    (SEX_FEMALE, 'Female'),
    (SEX_UNDEFINED, 'Undefined')
)

USER_NORMAL = "NORMAL"
USER_STAR = "STAR"

USER_LEVELS = (
    (USER_NORMAL, 'Normal'),
    (USER_STAR, 'Star')
)

INS_CONTENT_PICTURE = "PICTURE"
INS_CONTENT_VIDEO = "VIDEO"

INS_CONTENT_TYPES = (
    (INS_CONTENT_PICTURE, 'Picture'),
    (INS_CONTENT_VIDEO, 'Video')
)

INS_COMMENT = "COMMENT"
INS_LIKE = "LIKE"

COMMENT_TYPES = (
    (INS_COMMENT, 'Comment'),
    (INS_LIKE, 'Like')
)

INS_HOTTEST = "HOTTEST"
INS_NORMAL = "NORMAL"

INS_LEVELS = (
    (INS_HOTTEST, 'Hottest'),
    (INS_NORMAL, 'Normal')
)
