# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ins.models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COMMENT', 'Comment'), ('LIKE', 'Like')], default='LIKE', max_length=12)),
                ('body', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ins',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, default='', max_length=1024)),
                ('type', models.CharField(choices=[('PICTURE', 'Picture'), ('VIDEO', 'Video')], default='PICTURE', max_length=12)),
                ('content', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.CharField(blank=True, db_index=True, default='', max_length=256)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('avatar', models.CharField(max_length=256)),
                ('location', jsonfield.fields.JSONField(blank=True, default={})),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNDEFINED', 'Undefined')], default='UNDEFINED', max_length=12)),
                ('brief', models.CharField(blank=True, default='', max_length=512)),
                ('level', models.CharField(choices=[('NORMAL', 'Normal'), ('STAR', 'Star')], default='NORMAL', max_length=12)),
                ('followed', models.ManyToManyField(related_name='followers', to='ins.User')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', ins.models.INSUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='ins',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ins.Ins'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins.User'),
        ),
    ]
