# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import ins.models


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ins.models.INSUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
