# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins', '0002_auto_20170117_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
